spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643704759621-2t3k1a4ms551scrt30p71379etdequdf.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: g_brb0F8AQhUNQ3nfeZI
            client-secret: e54xv9Wcw6
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 1a2b72df14f6f65c13cb42a605fdfdca
            client-secret: GflWbLcl5aHAmTMi0cgJ82c4KJIY4aN5
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
